openapi: 3.0.0
info:
  title: Recipes App
  description: Gerenciamento de receitas
  version: 1.0.0
servers:
  - url: https://myrecipesserver-4wgv.onrender.com
    description: Produção
  - url: http://localhost:8080
    description: Local
paths:
  /recipes:
    get:
      summary: Obter receitas
      description: Obtém as receitas do usuário autenticado, opcionalmente filtrando por categoria
      tags:
        - Receitas
      security:
        - BearerAuth: []
      parameters:
        - name: category
          in: query
          description: Categoria da receita (opcional)
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Receitas retornadas com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipesResponse'
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Requisição inválida
    post:
      summary: Adicionar uma nova receita
      description: Adiciona uma nova receita com os detalhes fornecidos
      tags:
        - Receitas
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUpdateRecipesRequest'
      responses:
        '201':
          description: Receita adicionada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Requisição inválida
        '500':
          description: Erro interno do servidor
  /recipes/{id}:
    get:
      summary: Obter detalhes de uma receita
      description: Obtém os detalhes de uma receita específica
      tags:
        - Receitas
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID da receita
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da receita retornados com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipesResponse'
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Receita não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Requisição inválida
    delete:
      summary: Deletar uma receita
      description: Deleta uma receita específica
      tags:
        - Receitas
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID da receita
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Receita deletada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Receita não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Requisição inválida
        '500':
          description: Erro interno do servidor
    put:
      summary: Atualizar uma receita
      description: Atualiza os detalhes de uma receita específica
      tags:
        - Receitas
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID da receita
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddUpdateRecipesRequest'
      responses:
        '200':
          description: Receita atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Receita não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Requisição inválida
        '500':
          description: Erro interno do servidor
  /recipes/search:
    get:
      summary: Pesquisar receitas
      description: Pesquisa receitas do usuário autenticado por título ou ingredientes
      tags:
        - Receitas
      security:
        - BearerAuth: []
      parameters:
        - name: titleOrIngredient
          in: query
          description: Título ou ingredientes da receita
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Receitas encontradas com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipesResponse'
        '401':
          description: Não autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Requisição inválida
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Autenticação Bearer para acessar endpoints protegidos
  schemas:
    AddUpdateRecipesRequest:
      type: object
      properties:
        title:
          type: string
        category:
          type: integer
        preparationTime:
          type: integer
        preparationMode:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/IngredientsRequest'
      required:
        - title
        - category
        - preparationTime
        - preparationMode
    IngredientsRequest:
      type: object
      properties:
        product:
          type: string
        amount:
          type: string
    ErrorResponse:
      type: object
      properties:
        httpCode:
          type: integer
        message:
          type: string
    RecipesResponse:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        category:
          type: string
        totalIngredients:
          type: integer
        preparationTime:
          type: integer
    SimpleResponse:
      type: object
      properties:
        isSuccessful:
          type: boolean
        message:
          type: string
