name: Ktor CI Pipeline

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Ktor application
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run UserRoutesTest
        run: ./gradlew test --tests "application.routes.UserRoutesTest"

      - name: Run RecipesRoutesTest
        run: ./gradlew test --tests "application.routes.RecipesRoutesTest"

      - name: Run remaining tests
        run: ./gradlew test -x test --tests "application.routes.UserRoutesTest" --tests "application.routes.RecipesRoutesTest"
